### ISSUE TITLE
"Property value is not valid" when setting Build Action to "SpecFlowFeature"

### ISSUE THREAD

**Issue by johnknoop** [gasparnagy/SpecFlow.xUnitAdapter#11]
I'm following the steps outlined in the readme file, but I cant complete step 2, since neither of SpecFlowFeature nor SpecFlowEmbeddedFeature are valid values for the Build Action property of my .feature file.

Anyone else ran in to this?

**Comment by johnknoop** [comment]
If I just set "Copy to Output Directory" to "Copy always", the test gets discovered by VS Test Explorer. But when I run it, it complains about not finding NUnit. We're not using NUnit, we're using XUnit.

This is the stacktrace:

>Message: System.IO.FileNotFoundException : Could not load file or assembly 'nunit.framework' or one of its dependencies. The system cannot find the file specified.

These NuGet packages are installed:

```
  <package id="SpecFlow" version="2.2.1" targetFramework="net461" />
  <package id="SpecFlow.Assist.Dynamic" version="1.3.1" targetFramework="net461" />
  <package id="SpecFlow.xUnit" version="2.2.1" targetFramework="net461" />
  <package id="SpecFlow.xUnitAdapter" version="1.1.0" targetFramework="net461" />
  <package id="xunit" version="2.3.1" targetFramework="net461" />
  <package id="xunit.abstractions" version="2.0.1" targetFramework="net461" />
  <package id="xunit.analyzers" version="0.8.0" targetFramework="net461" />
  <package id="xunit.assemblyfixture" version="2.0.3" targetFramework="net461" />
  <package id="xunit.assert" version="2.3.1" targetFramework="net461" />
  <package id="xunit.core" version="2.3.1" targetFramework="net461" />
  <package id="xunit.extensibility.core" version="2.3.1" targetFramework="net461" />
  <package id="xunit.extensibility.execution" version="2.3.1" targetFramework="net461" />
  <package id="xunit.runner.visualstudio" version="2.3.1" targetFramework="net461" developmentDependency="true" />
```

**Comment by johnknoop** [comment]
Also, there are some warnings when I build the test project:

> [2017-12-27 13:14:10 Error] Unable to fetch symbols for class: MySteps
[2017-12-27 13:14:10 Error] Unable to fetch source Information for test method: MySteps.My test: Tests.

**Comment by ChristopherHaws** [comment]
It looks like maybe you didnt create an app.config file which specflow requires. Mine looks like this and it works:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  
  <configSections>
    <section name="specFlow" type="TechTalk.SpecFlow.Configuration.ConfigurationSectionHandler, TechTalk.SpecFlow" />
  </configSections>
  
  <specFlow>
    <unitTestProvider name="xUnit" />
    <plugins>
      <add name="SpecFlow.xUnitAdapter" type="Runtime" />
    </plugins>
  </specFlow>

</configuration>
```

**Comment by johnknoop** [comment]
Hi

I tried to re-install the Nuget package from scratch again, and this time it worked!

Thanks
