### ISSUE TITLE
"Could not find a source mapping" despite passing tests

### ISSUE THREAD

**Issue by johnknoop** [gasparnagy/SpecFlow.xUnitAdapter#13]
Hi

When running the tests in the xunit console runner, it outputs "Could not find a source mapping". This sounds like something is wrong. But the tests actually pass. No showstopper for us, just thought you should know.

**Comment by ChristopherHaws** [comment]
Can you provide some additional details about your project? Specifically what I am looking for is:

Is it using the new project system?
Are you using packages.config, project.json, or PackageReference for nuget?
What framework are you targeting?
What version of Visual Studio are you using?
Are you using embedded feature files?

Thanks!
Chris

**Comment by johnknoop** [comment]
Hi

It's not a .NET Core project, it's a .NET Framework 4.7. Visual Studio 2017. Feature files are not embedded, because neither SpecFlowFeature nor SpecFlowEmbeddedFeature can be found in the Build Action dropdown, and entering it manually isn't accepted by VS. But I managed to get it running anyway, by changing Copy To Output Folder to "Always".
