### ISSUE TITLE
Unable to select Build Action as per Readme

### ISSUE THREAD

**Issue by Devvox93** [gasparnagy/SpecFlow.xUnitAdapter#15]
In VS 2017, I Installed the necessary SpecFlow packages, made some feature files and emptied the "Custom Tool" property.
However, I can not enter SpecFlowFeature or SpecFlowEmbeddedFeature as "Property value is invalid".
I've double-checked all steps and seen your video (where you don't set it that way btw).
Did I miss something or is it a bug?

The test project builds fine, but on building it adds the .cs code-behind files again.
I should mention that I'm using .NET Core. The example project works fine.

**Comment by petermorlion** [comment]
I have the same issue in a .NET 4.6.2 library.

**Comment by Devvox93** [comment]
> I think it could be due to the new csproj layout, not specifically .NET Core.
In that case, I think it would be solved if SpecFlow itself implements support for the new csproj layout.
It is currently being worked on: https://github.com/techtalk/SpecFlow/pull/649

**Comment by gasparnagy** [comment]
.NET core and and the new project format is not supported by the build actions. I will add this to the readme.md
