### ISSUE TITLE
Scenarios don't show in resharper

### ISSUE THREAD

**Issue by rwilliamshgem** [gasparnagy/SpecFlow.xUnitAdapter#18]
Hi,

I followed your instructions in your readme file and got it working under mstest explorer but when i try to see my scenarios in resharper they don't appear. Is there anything I need to do to get it to work with resharper?

Thanks!

**Comment by gasparnagy** [comment]
We use the xUnit custom test framework feature, that is probably not supported by ReSharper. I recommend contacting them for clarification.
