### ISSUE TITLE
[Discussion] MSBuild Integration

### ISSUE THREAD

**Issue by ChristopherHaws** [gasparnagy/SpecFlow.xUnitAdapter#4]
I have created branches for a few features that rely on MSBuild tasks. I wanted to open a discussion to discuss if this is the approach we should take to make sure I am not going off in the complete wrong direction.

Some of the features I was able to get working using MSBuild tasks:
- Adding source maps to the feature file build artifacts (embedded and non-embedded)
- Feature file build validation that returns errors to the error log with the correct line/column numbers so IDE integration works.
- Integration with the new csproj system without having to modify the csproj file

Should we be sticking to MSBuild integration as much as possible? I think this will give us the most flexibility. The more MSBuild integrated the process is, the more cross platform and tool agnostic it will be.

**Comment by gasparnagy** [comment]
I am closing this topic as this is anyway integrated to the solution.
