### ISSUE TITLE
Causes problem with ITestOutputHelper

### ISSUE THREAD

**Issue by markdoth** [gasparnagy/SpecFlow.xUnitAdapter#8]
In order to log messages to output when running xUnit tests, I'm using the method that is demonstrated in this sample: https://github.com/aptester/SpecflowSamples

When I add xUnitAdapter and remove the code behind files to this solution it's causing a problem with the context injection step:

        public CalcContext(ScenarioContext context)
        {
            ..
            Output = context.ScenarioContainer.Resolve<ITestOutputHelper>();
        }

Which throws

Message: BoDi.ObjectContainerException : Interface cannot be resolved: Xunit.Abstractions.ITestOutputHelper

Any idea why this is breaking or if there is a workaround?

**Comment by gasparnagy** [comment]
I need to check this, but I can only do it after next week.

**Comment by markdoth** [comment]
Much appreciated - I'll look out for the update.

Removing the code behind is going to really help us getting our BA's more comfortable editing feature files in Visual Studio and simplify our code review / merge, so really appreciate the work you're doing here.

**Comment by gasparnagy** [comment]
@markdoth this is fixed now, I will release a new version tomorrow
